  cfg : { 'frame' : 2,
          'dist_w' : 2.,
          'free_w' : 0.,
          'TEMPORAL_RANGE' : 5,
          'sc_w' : 1.,
          'lr' : 0.03,
          'trunc_dist' : 0.5,
          'passing_ids' : True,
          'K' : 16,
          'd_thre' : 0.03,
          'eps' : 0.3,
          'min_samples' : 1,
          'iters' : 1,  # Experiments run with 1500
          
          # Data:
          'max_radius' : 35.0,
          'max_height' : 3.0,
          'min_height' : 0,
          
          # Choose Models:
          'model' : 'let_it_flow',
          # 'model' : 'MBNSFP',
          # 'model' : 'chodosh',
          # 'model' : 'NP',
          

          # Folders:
          'folder_path' : 'datasets/argoverse2/',
          'store_path' : 'datasets/argoverse2/',

          # Devices:
          'device' : 'cuda:0',
          'nbr_of_devices' : 1,    
  }